version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 6
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 4
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - "navikt/eessibasis"
    labels:
      - "dependencies"
      - "automerge"
